# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo $(TESTVARIABLE)
    echo Tony World
  displayName: 'Run a multi-line script'

- script: |
    pwd
    echo Printing directory contents':'
    ls
  displayName: 'LS'

- task: ShellScript@2
  inputs:
    scriptPath: BashDemo.sh
  displayName: 'Shell scriptPath'

- task: Bash@3
  inputs:
    targetType: filePath
    filePath: 'BashDemo.sh'
    #script: BasheDemo.sh
  displayName: 'Run BashDemo FilePath Script File from yml'

- task: Bash@3
  inputs:
    script: BashDemo.sh
  displayName: 'Run just Script File from yml'

- task: Bash@3
  inputs:
    targetType: inline
    script: echo "TestWorkingYAMLBASH Tony"
  displayName: 'Bash inline Echo'

- bash: BashDemo.sh

- bash: echo "In line Bash command test"